### PR TITLE
Add PlatformIO

### PR DESCRIPTION
**Pull request by ajschmidt8**
This PR contains the following changes: 

- Reverts #16
- Merges `master` into `dev` to get the latest stable changes
- Adds PlatformIO build capability (by cherry picking https://github.com/maxgerhardt/AlarmDecoder-STSDK/commit/d216415d9887d786d67344407aee10535cd05a86 from the [PIO thread](https://community.platformio.org/t/no-such-file-or-directory-with-esp32-project/19856))
- Adds `st-device-sdk-c` repo as a submodule for PIO building
- Update `.gitignore`
- Remove the `component.mk` files since they seem to be from `v3` of `esp-idf` and we're now using `v4` (which switches to CMake)
- Updates the changelog

@f34rdotcom, let me know your thoughts on this. If you have the `pio` CLI installed ([installation docs](https://docs.platformio.org/en/latest/core/installation.html#installation-methods)), you _should_ (:crossed_fingers:) be able to run `pio run` in this repo now to generate a successful build.

### CODE REVIEW

**Comment by ajschmidt8** [comment]
hmm. CI is complaining about the submodule. I'll take a look

**Comment by f34rdotcom** [comment]
> hmm. CI is complaining about the submodule. I'll take a look

Looks like we can add exclude args to the astyle config file. Just need to limit where the script works. 

https://github.com/steinwurf/astyle/blob/master/.astylerc

**Comment by ajschmidt8** [comment]
whoops. just saw this comment. let me update the config file, that's cleaner than my previous commit

**Comment by ajschmidt8** [comment]
wow. okay, finally got it. the `exclude` command didn't seem to play nice with the `find` command. I removed the `find` command and moved some args to the `.astylerc` file. But then `astyle` started spitting out the 4 lines below into the `astyle.out` file, so I had to account for those in the conditional statement.

```
------------------------------------------------------------
Directory  /home/travis/build/nutechsoftware/AlarmDecoder-STSDK/*.cpp,*.h
Exclude  st-device-sdk-c
------------------------------------------------------------
```

**Pull request merged**
